### ISSUE TITLE
package.json file not fully populated

### ISSUE THREAD

**Issue by tekstrong** [dracula/nylas-n1#4]
![error](https://cloud.githubusercontent.com/assets/11777486/18445359/36726a46-78eb-11e6-8d01-8d7656573e88.jpg)

The package.json appears to be a blank template file? Following the current install directions on https://github.com/dracula/nylas-n1/ will result in the theme install failing. Manually filling in this info did not resolve the issue, as it does then show up in the theme picker, but fails to display and then crashes the picker until I manually remove the created theme folder from ~/.nylas

(Note: On 9/6 Nylas sent out an email titled "Twenty stunning themes for Nylas N1" which is how I came across your, possibly stunning, theme. Hate to see folks find this great theme only to be turned away by it not installing/working.)

**Comment by zenorocha** [comment]
Hey @benjamingarcia, can you take a look?

**Comment by zenorocha** [comment]
@tekstrong could you send a pull request?

**Comment by zenorocha** [comment]
Fixed! Thanks for reporting @tekstrong and thanks @Croccifixio for fixing it ;)
