### ISSUE TITLE
Project link on GitHub page does not exist

### ISSUE THREAD

**Issue by tekstrong** [dracula/nylas-n1#5]
Clicking on the project link...
![dracula_nylas_badlink](https://cloud.githubusercontent.com/assets/11777486/18446033/586a8518-78ee-11e6-9c52-516ef46ecd7b.png)

...currently gets you a nice, minimal 404 page:
![error2](https://cloud.githubusercontent.com/assets/11777486/18446038/5dcb300c-78ee-11e6-86e2-0eb5d242e074.jpg)

**Comment by zenorocha** [comment]
Thanks a lot for pointing it out. We didn't have the chance to include the Nylas section on the site yet.
