### ISSUE TITLE
Any hope to see it for Mailspring?

### ISSUE THREAD

**Issue by Ansem93** [dracula/nylas-n1#9]
Hi!
There is some hope to see this skin for Mailspring??

**Comment by benjamingarcia** [comment]
Hi! 
Well, I don't know. I don't test MailSpring...

**Comment by j1012** [comment]
Does not work on MailSpring

**Comment by shelmus** [comment]
I followed instructions listed here for Mailspring but its still now allowing the import.
https://foundry376.zendesk.com/hc/en-us/articles/115001918391
This persons fork seems to import but its not great.
https://github.com/nickolasclarke/mailspring-dracula

**Comment by zenorocha** [comment]
https://github.com/dracula/mailspring ;)
